# Generated by Django 6.0 on 2026-01-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('location', models.CharField(db_index=True, max_length=100)),
                ('job_count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Job Data',
                'verbose_name_plural': 'Job Data',
                'ordering': ['-date', 'location'],
                'indexes': [models.Index(fields=['date', 'location'], name='dashboard_j_date_8a6c87_idx')],
                'unique_together': {('date', 'location')},
            },
        ),
    ]
